
before_script:
  - cd ..
  - hg clone https://bitbucket.org/vim-mirror/vim
  - cd vim
  - hg log -v -r -1:-4
  - cp -r ../vim-ktakata-mq .hg/patches
  - cd src
  - hg --config extensions.mq= --config "ui.username=$USER <$USER@$HOSTNAME>" qpush -a
  - make
  - ./vim --version

script:
  - make test

# vim: ts=2 sw=2 sts=2 et
