version: 1.0.{build}

image:
  - Visual Studio 2015
  - Ubuntu

environment:
  matrix:
  - ARCH: x64
  - ARCH: x86
  - ARCH: x86_64

matrix:
  exclude:
    - image: Visual Studio 2015
      ARCH: x86_64
    - image: Ubuntu
      ARCH: x64
    - image: Ubuntu
      ARCH: x86

for:
  -
    matrix:
      only:
        - image: Visual Studio 2015
          ARCH: x64
    environment:
      PYTHON2_DIR: C:\Python27-x64
      PYTHON3_DIR: C:\Python34-x64
  -
    matrix:
      only:
        - image: Visual Studio 2015
          ARCH: x86
    environment:
      PYTHON2_DIR: C:\Python27
      PYTHON3_DIR: C:\Python34
  -
    matrix:
      only:
        - image: Ubuntu
          ARCH: x86_64


install:
- cmd: |-
    "C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /%ARCH% /release
    set "INCLUDE=%INCLUDE%C:\Program Files (x86)\Windows Kits\8.1\Include\um"
- sh: |-
    sudo apt update -qq
    sudo apt-get install -y -qq libperl-dev python2.7-dev python3-dev liblua5.2-dev lua5.2 ruby-dev ruby tcl-dev libgtk-3-dev
    Xvfb :99 &
    export DISPLAY=:99.0
    rvm use system

build_script:
- cmd: |-
    cd ..
    hg clone https://bitbucket.org/vim-mirror/vim
    cd vim
    rem Show the recent commits in the Vim repository
    hg log -v -r -1:-4
    cd .hg
    mkdir patches
    xcopy /s %APPVEYOR_BUILD_FOLDER% patches > nul
    cd ..\src
    rem Apply all patches
    hg --config extensions.mq= --config "ui.username=%USERNAME% <%USERNAME%@%USERDOMAIN%>" qpush -a
    rem Suppress progress animation
    sed -e "s/@<<$/@<< | sed -e 's#.*\\\\r.*##'/" Make_mvc.mak > Make_mvc2.mak
    rem Build gvim
    nmake -f Make_mvc2.mak GUI=yes OLE=yes DIRECTX=yes PYTHON_VER=27 DYNAMIC_PYTHON=yes PYTHON=%PYTHON2_DIR% PYTHON3_VER=34 DYNAMIC_PYTHON3=yes PYTHON3=%PYTHON3_DIR%
    rem Build vim
    nmake -f Make_mvc2.mak GUI=no PYTHON_VER=27 DYNAMIC_PYTHON=yes PYTHON=%PYTHON2_DIR% PYTHON3_VER=34 DYNAMIC_PYTHON3=yes PYTHON3=%PYTHON3_DIR%
    rem Show gvim version
    start /wait .\gvim -silent -register
    start /wait .\gvim -u NONE -c "redir @a | ver | 0put a | wq!" ver.txt
    type ver.txt
    rem Print interface versions
    start /wait .\gvim -u NONE -S ..\.hg\patches\scripts\if_ver.vim -c quit
    type if_ver.txt
    rem Show vim version
    .\vim --version
    rem Print interface versions
    .\vim --not-a-term -u NONE -S ..\.hg\patches\scripts\if_ver.vim -c quit
    type if_ver.txt
- sh: |-
    cd ..
    hg clone https://bitbucket.org/vim-mirror/vim
    cd vim
    hg log -v -r -1:-4 --color=always | cat
    cp -r $APPVEYOR_BUILD_FOLDER .hg/patches
    cp .hg/patches/scripts/*.vim src
    cd src
    hg --config extensions.mq= qselect linux # pipelines
    hg --config extensions.mq= --config "ui.username=$USER <$USER@$HOSTNAME>" qpush -a
    make
    ./vim --version
    ./vim --not-a-term -u NONE -S if_ver-1.vim -c quit > /dev/null
    ./vim --not-a-term -u NONE -S if_ver-2.vim -c quit > /dev/null
    cat if_ver.txt

test_script:
- cmd: |-
    cd \projects\vim\src\testdir
    rem Testing with MSVC gvim
    nmake -f Make_dos.mak VIMPROG=..\gvim
    nmake -f Make_dos.mak clean
    rem Testing with MSVC vim
    nmake -f Make_dos.mak VIMPROG=..\vim
- sh: |-
    make test

# vim: ts=2 sw=2 sts=2 et
