# This is a sample build configuration for C++.
# Check our guides at https://confluence.atlassian.com/x/VYk8Lw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: gcc:6.1

pipelines:
  default:
    - step:
        script: # Modify the commands below to build your repository.
          - apt update -q
          - apt install -y -q libperl-dev python2.7-dev python3-dev liblua5.2-dev lua5.2 ruby-dev ruby tcl-dev man xvfb
          - Xvfb :99 -screen 0 1024x768x24 &
          - export DISPLAY=:99.0
          - cd ..
          - hg clone https://bitbucket.org/vim-mirror/vim
          - cd vim
          - hg log -v -r -1:-4
          - cp -r $BITBUCKET_CLONE_DIR .hg/patches
          - cp .hg/patches/scripts/*.vim src
          - cd src
          - hg --config extensions.mq= qselect linux pipelines
          - hg --config extensions.mq= --config "ui.username=$USER <$USER@$HOSTNAME>" qpush -a
          - make
          - ./vim --version
          - ./vim --not-a-term -u NONE -S if_ver-1.vim -c quit > /dev/null
          - ./vim --not-a-term -u NONE -S if_ver-2.vim -c quit > /dev/null
          - cat if_ver.txt
          - export -n DISPLAY
          - make test
          - if test -f testdir/messages; then cat testdir/messages; fi
          - if test -f testdir/test.log; then cat testdir/test.log; fi

# vim: ts=2 sw=2 sts=2 et
