# This is a sample build configuration for C++.
# Check our guides at https://confluence.atlassian.com/x/VYk8Lw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: gcc:6.1

pipelines:
  default:
    - step:
        script: # Modify the commands below to build your repository.
          - apt update
          - apt install -y libperl-dev python2.7-dev python3-dev liblua5.2-dev lua5.2 ruby-dev ruby tcl-dev
          - cd ..
          - hg clone https://bitbucket.org/vim-mirror/vim
          - cd vim
          - hg log -v -r -1:-4
          - cp -r $BITBUCKET_CLONE_DIR .hg/patches
          - cd src
          - hg --config extensions.mq= qselect linux
          - hg --config extensions.mq= --config "ui.username=$USER <$USER@$HOSTNAME>" qpush -a
          - make
          - ./vim --version
          - ./vim -u NONE -S $BITBUCKET_CLONE_DIR/scripts/if_ver.vim -c quit
          - ./vim -u NONE -S $BITBUCKET_CLONE_DIR/scripts/if_ver_py3.vim -c quit
          - cat if_ver.txt
          - export -n DISPLAY
          - make test

# vim: ts=2 sw=2 sts=2 et
